import React from "react";
import Link from "next/link";
import Image from "next/image";

/**
 * MDXComponent Mapper
 *
 * Maps standard HTML elements generated by MDX into our custom
 * Tailwind-styled React components. This ensures all markdown content
 * seamlessly inherits the "Monochromatic Neo-Analog" aesthetic without
 * needing to write HTML/Tailwind directly in the markdown files.
 */
export const MdxComponents = {
  h1: (props: React.ComponentPropsWithoutRef<"h1">) => (
    <h1
      className="text-4xl md:text-5xl font-bold mt-12 mb-6 tracking-tight text-neutral-100"
      {...props}
    />
  ),
  h2: ({ children, ...props }: React.ComponentPropsWithoutRef<"h2">) => {
    const id =
      typeof children === "string"
        ? children
            .toLowerCase()
            .replace(/[^\w]+/g, "-")
            .replace(/(^-|-$)/g, "")
        : undefined;
    return (
      <h2
        id={id}
        className="text-3xl md:text-4xl font-bold mt-10 mb-4 tracking-tight text-neutral-200 border-b border-neutral-800 pb-2 scroll-mt-24"
        {...props}
      >
        {children}
      </h2>
    );
  },
  h3: ({ children, ...props }: React.ComponentPropsWithoutRef<"h3">) => {
    const id =
      typeof children === "string"
        ? children
            .toLowerCase()
            .replace(/[^\w]+/g, "-")
            .replace(/(^-|-$)/g, "")
        : undefined;
    return (
      <h3
        id={id}
        className="text-2xl font-bold mt-8 mb-4 text-neutral-300 scroll-mt-24"
        {...props}
      >
        {children}
      </h3>
    );
  },
  p: (props: React.ComponentPropsWithoutRef<"p">) => (
    <p
      className="leading-relaxed text-neutral-400 font-serif mb-6 text-[1.05rem] md:text-lg"
      {...props}
    />
  ),
  a: (props: React.ComponentPropsWithoutRef<"a">) => {
    const href = props.href;
    const isInternalLink =
      href && (href.startsWith("/") || href.startsWith("#"));

    const baseClasses =
      "text-neutral-200 underline decoration-neutral-600 underline-offset-4 hover:decoration-white transition-colors cursor-pointer font-mono text-sm md:text-base";

    if (isInternalLink) {
      return <Link href={href} className={baseClasses} {...props} />;
    }
    return (
      <a
        target="_blank"
        rel="noopener noreferrer"
        className={baseClasses}
        {...props}
      />
    );
  },
  ul: (props: React.ComponentPropsWithoutRef<"ul">) => (
    <ul
      className="list-disc list-outside mb-6 pl-6 text-neutral-400 font-serif text-lg space-y-2 marker:text-neutral-600"
      {...props}
    />
  ),
  ol: (props: React.ComponentPropsWithoutRef<"ol">) => (
    <ol
      className="list-decimal list-outside mb-6 pl-6 text-neutral-400 font-serif text-lg space-y-2 marker:text-neutral-600"
      {...props}
    />
  ),
  li: (props: React.ComponentPropsWithoutRef<"li">) => (
    <li className="pl-2" {...props} />
  ),
  blockquote: (props: React.ComponentPropsWithoutRef<"blockquote">) => (
    <blockquote
      className="border-l-4 border-neutral-600 pl-6 italic my-8 text-neutral-300 bg-neutral-900/30 py-4 pr-4 rounded-r-md"
      {...props}
    />
  ),
  pre: ({ children, ...props }: React.ComponentPropsWithoutRef<"pre">) => (
    <div className="relative my-8 group">
      <div className="absolute -inset-y-2 -inset-x-4 bg-neutral-900/50 rounded-xl z-0 hidden md:block opacity-0 group-hover:opacity-100 transition-opacity" />
      <pre
        className="relative z-10 bg-[#050505] border border-neutral-800 rounded-lg p-4 overflow-x-auto font-mono text-sm text-neutral-300 shadow-2xl shadow-black/50"
        {...props}
      >
        {children}
      </pre>
    </div>
  ),
  code: ({
    className,
    children,
    ...props
  }: React.ComponentPropsWithoutRef<"code">) => {
    const isInline = !className;
    return isInline ? (
      <code
        className="bg-neutral-900 text-neutral-300 px-1.5 py-0.5 rounded-md border border-neutral-800 font-mono text-[0.85em]"
        {...props}
      >
        {children}
      </code>
    ) : (
      <code className={className} {...props}>
        {children}
      </code>
    );
  },
  strong: (props: React.ComponentPropsWithoutRef<"strong">) => (
    <strong className="font-bold text-neutral-200" {...props} />
  ),
  hr: (props: React.ComponentPropsWithoutRef<"hr">) => (
    <hr className="my-10 border-neutral-800" {...props} />
  ),
  // Allow for custom Next.js Image component inside MDX
  Image: ({ alt, ...props }: React.ComponentPropsWithoutRef<typeof Image>) => (
    <div className="my-10 relative w-full h-[300px] md:h-[500px] rounded-lg overflow-hidden border border-neutral-800 group bg-neutral-900">
      <Image
        fill
        className="object-cover grayscale group-hover:grayscale-0 transition-all duration-700 ease-in-out group-hover:scale-105"
        alt={alt || "Blog image"}
        {...props}
      />
      <div className="absolute inset-0 bg-black/20 group-hover:bg-transparent transition-colors duration-500 pointer-events-none" />
    </div>
  ),
};
